// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
// Package lazy renders the HTMX lazy-load pattern: a page returns its

// shell immediately with a placeholder box, and that box fetches the

// real (slow) content in a second request on load. This keeps the menu

// + topbar + page chrome interactive while Mongo / CRM enrichment runs.

//

// Usage — the page renders its shell (layout, header, action bar) and

// drops a stable content wrapper holding the lazy box, passing the

// placeholder to show while loading as children (a table page passes a

// skeleton shaped like its real table):

//

//	<div id="payments-content">

//		@lazy.Content("/rekon/payments/content?"+query) {

//			@skeleton.Table(headers, skeleton.DefaultRows)

//		}

//	</div>

//

// The page's own handler stays split in two: the shell route returns the

// markup above (no data fetch); the contentURL route does the fetch and

// returns the real fragment. Filter / pagination HTMX swaps keep

// targeting the stable wrapper (#payments-content here).

package lazy

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// Content renders a placeholder box that, on insertion (hx-trigger=load),
// GETs contentURL and replaces ITSELF (hx-swap=outerHTML on this) with
// the response. Because it self-replaces, the page's surrounding wrapper
// (e.g. #payments-content) survives for later filter / pagination swaps.
// The children render as the loading placeholder (pass a skeleton).
func Content(contentURL string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div hx-get=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(contentURL)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `view/lazy/lazy.templ`, Line: 30, Col: 21}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" hx-trigger=\"load\" hx-target=\"this\" hx-swap=\"outerHTML\" aria-busy=\"true\" data-kiban-lazy>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
